### ISSUE TITLE
Audible alert for Battery Applet

### ISSUE THREAD

**Issue by clarity-phev** [pdcurtis/cinnamon-applets#4] opened 2017-02-03 02:51 UTC
Peter:

Thanks for contributing the excellent applet...  it is just what I was looking for !!
In your documentation, you include the following statement:

> For full facilities including notifications and audible alerts the zenity sox and libsox-fmt-mp3 libraries must be installed. They can be installed with the Synaptic Package Manager or using the following terminal command:
>     sudo apt-get install zenity sox libsox-fmt-mp3

An audible alert is important to me, but it is not clear what must be done to enable this feature.  I installed the two libraries as instructed, but I do not get an audible alert.

Can you please elaborate on what is needed to activate the audible feature?

I am running Linux MInt 18.1 Cinnamon.

-Thanks
 Tom

**Comment by pdcurtis** [comment] 2017-02-04 14:24
Thanks for you favourable comments

There should be an audible alert when a suspend is imminent once those programs are installed.

There is currently no audible warning when the Modal Alert box is put up at the warning level as that was considered adequate and impossible to miss if you are using the machine and remains present until you return unlike a brief audible warning.

I have checked it is working on the two machines accessible to be. If you still have a problem check you audio settings as the applet does not override you settings for device and volume. If you still have a problem let me know otherwise I will close the issue  after a week or two. 

I will also make the documentation more clear.

It would be possible to add an option for an earlier audible warning the next time I update the applet, if users consider it desirable.
Peter

**Comment by clarity-phev** [comment] 2017-02-04 14:46
Peter:

With your additional explanation, I believe the audible is working as intended.

I would like to encourage you to include a [possibly different] audible along with the initial Modal Alert box.  I am often not actively "using the machine", but I am in the room.  Maybe the screen has turned off as part of the power saving regime...  With the earlier warning sound, it reminds me to take action - wake up from my snooze, plug in, save, etc. before suspend is imminent.

I have also learned by exploring your code that it is easy to choose a different sound by altering 'suspendScript' in your local directory tree.

-Tom

**Comment by pdcurtis** [comment] 2017-02-04 18:12
Tom

If you want to try some simple modifications it should be quite simple to modify the code. I am myself off the coast of South America and Internet is both expensive and unreliable and I am also tied up try to get everything working correctly and documented on the new Cinnamon Applet Web Site using their own Github Repository

You could change the call to the Modal Dialog to another script call (say alertScript) or even just call sox directly.

**_Following is not tested_** but you could try change code around line 300 to something like one of these two options and optionally comment out the two Modal Alert lines

```
if (this.batteryState.indexOf("discharg") > -1) {
                    this.batteryMessage = "Battery Low - turn off or connect to mains ";
                    if ( !this.alertFlag) {
                       this.alertFlag = true;  // Reset above when out of warning range
//                     Tests of audible alert
//                     GLib.spawn_command_line_async('sh ' + this.appletPath + '/alertScript');
//                     or
//                     GLib.spawn_command_line_async('play "/usr/share/sounds/freedesktop/stereo/alarm-clock-elapsed.oga"');
                       alertModalDataWarning = new AlertDialog("The Battery Level has fallen to your alert level\n\n either reconnect to a power source\n\or close down your work and suspend or shutdown the machine");
                       alertModalDataWarning.open();

                    } 
                } 
```
Back your machine up first.

Remember you will need a cinnamon restart before you see anything change by Ctrl Alt Esc

**Comment by clarity-phev** [comment] 2017-02-05 02:06
Peter:

Sounds good.

I had already tried something almost precisely as you propose...  I think it is working, but I haven't fully tested it yet.

While testing, I found that I could affect changes by removing and re-adding the applet from the panel, but the Ctrl Alt Esc sounds easier.

Along the way, while testing, I got caught in a nasty loop where the battery was below the critical level.  I would try to cancel the suspend, but the suspend dialog box kept recurring over and over again.  I think I escaped this loop by plugging in, but it was a little awkward.  I'm sure there's a better way to test things, but I'm pretty sure I have the initial audible working.

Thanks for the help, and please consider incorporating the early alarm feature more formally if you have some time in the future.

-Tom

**Comment by pdcurtis** [comment] 2017-02-05 16:51
Tom,

I do not like the sound of the looping - let me know if you find the cause so I can make sure it is just in the mods and can not effect the main applet. 

I am also quite happy if you send in a patch for your final changes - I just don't have the time to do all the testing I like before issuing anything.

Also note all approved  applets now have to be on https://github.com/linuxmint/cinnamon-spices-applets so my own repository will eventually be superseded and I lose much of the control. 

Peter

**Comment by clarity-phev** [comment] 2017-02-06 14:06
Peter:

The App is definitely going haywire and initiating a nasty loop.  The only way I can find to get out of the loop is by slamming the power off.  I believe the problem stems from something with my laptop (an Asus ZenBook).  For some reason, the battery status reports 'discharging' even when it is plugged in and charging.  I do not have this problem in Windows, only Linux.  Since the App always thinks the battery is discharging it is hell-bent on reporting alerts and suspending even though it shouldn't when plugged in... 

Maybe something could be done with the logic in the App such that it doesn't get out of control, but I think the fundamental problem is that my laptop is misbehaving, so I will go off and chase that problem for a while.

-Tom

**Comment by pdcurtis** [comment] 2017-02-18 14:58
Does the built in power applet show the discharging event correctly or is it just my applet? The built in applet ( power@cinnamon.org ) uses a different and more complex way of obtaining the battery information but the results should be the same.

I am thinking of adding an option to switch off the suspend action in the configuration and in the menu and also to inhibit it automatically after say five calls to the suspend routine to break any loops. An audible alert could remain for longer. 

It is more difficult to find a fool proof way to automatically re-enable automatic suspend it if the discharging/charging state can not be relied on. Is fully charged reliably identified on your machine and does the percentage charge reliably increase when charging and decrease when discharging or are there glitches?

Peter

**Comment by clarity-phev** [comment] 2017-02-19 03:21
I don't think I have seen a disagreement between power@cinnamon.com and batterymonitor@pdcurtis.

My laptop is plugged in most of the time, and the apps always indicate 'using battery power', and 'discharging' respectively when fully charged and plugged in.  This seems abnormal to me, but I don't really have another frame of reference to know for sure.

I don't think I normally experience this false 'discharging' state when plugged in if the battery is actually low.  It's just when the charge is full (maybe 95+ percent), then It always indicates 'discharging'.

I have been using 'batterymonitor' with the patch to provide the early audible.  I don't seem to get stuck in any loops with normal operation.  The looping was occurring when I was testing / debugging by moving the slider bar around in order to trigger warnings without waiting so long.  I also had your 'test' feature enabled which divides the actual percentage by 5.

In any event, I am currently content when I'm just using the applet as intended and not fooling around with debugging, etc.  I would prefer if the status would never indicate 'discharging' when actually plugged in, but this doesn't seem to affect applet behavior under normal circumstances.

**Comment by pdcurtis** [comment] 2017-02-21 21:30
Thanks for the feedback. I may still look at a way to limit the number of suspends in a short time but it does sound as if you have an unusual problem with your laptop. I have occasionally seen laptops 'stick' for a while at 98 or 99% but I have never seen the discrepancies you describe. You might want to raise an issue against the cinnamon power monitor if you have done searches to see if others have the problem - I suspect it is in the kernel / ACPI  but it will at least alert others to the problem.

I will also add the audible alert to the next version. How exactly did you finally implement it as there is no point in my using a different way when you have done a lot of testing.

**Comment by clarity-phev** [comment] 2017-02-21 21:57
All I did was add the 'GLib.spawn_command_line_async...' line to 'applet.js' as follows:

    this.batteryMessage = "Battery Low - turn off or connect to mains ";
     if ( !this.alertFlag) {
        this.alertFlag = true;  // Reset above when out of warning range
        GLib.spawn_command_line_async('play "/home/tom/.local/share/cinnamon/applets/batterymonitor@pdcurtis/Losing power.mp3"');// Play an early warning audible message
        alertModalDataWarning = new AlertDialog("The Battery Level has fallen to your alert level\n\n either reconnect to a power source\n\or close down your work and suspend or shutdown the machine");
        alertModalDataWarning.open();      
     }
}

I don't prefer altering the main code like this, and would rather if it were in a separate configuration file or script (maybe similar to the 'suspendScript')?

**Comment by pdcurtis** [comment] 2017-04-30 08:16
Latest version has the audible alert.

**Closed as completed by pdcurtis** 2017-04-30 08:16 UTC
